/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class appIcons {
  appIcons._();

  static const _kFontFam = 'appIcons';
  static const String? _kFontPkg = null;

  static const IconData arrow_eggshell_white = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_pure_white = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cafe_selected = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cafe_unselected = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData club_selected = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData club_unselected = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_selected = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_unselected = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_white = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music_note_selected = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music_note_unselected = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_selected = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_unselected = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_black = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
