/// Flutter icons CustomIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: assets/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData map = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wapp_team = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData description = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music_note = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData miscellaneous = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData announcements = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cafe = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData club = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification_selected = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification_unselected = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification_ringing = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification_filled_ringing = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
