/// Flutter icons Upvote
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Upvote
///      fonts:
///       - asset: fonts/Upvote.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Upvote {
  Upvote._();

  static const _kFontFam = 'Upvote';
  static const String? _kFontPkg = null;

  static const IconData unupvoted = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upvoted = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
